language: go
go:
- 1.8.x
- tip
before_install:
- chmod +x test-coverage.sh
- go get -t -v ./...
script:
- "./test-coverage.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: L8iGnBf4sZnqKGV4mlekwRzD+jHVUuIQ+hY/8v2HF1toGDNFuBU5ftoo9MdA5bU3JqFSouxje6ZwpQ/hKHvcXVQHAWs3kWAo+6BCg0PQNqD/LBXFd4WbvUawx9qz2/CwOrK7nOrki+1Ur6I96QMAcvNX0vegmCec7qIrSVC2nGcyqoPmA1+cLtbczkLOm+yA6lTyNXYCAs7tJZ1p2ny3CpG5HDXy3vdxM68Rdh4UkhtSBPikOFGbQnnVO048j8BBn3SwxtXPZN8ZSNl9WY6AlBYb6X3hA01piCmXa5JQcwd8rPOoEKopppmEaU4vczAsMFnG3232lhPm9CH/nQ7KOSoHVtam0nhSERLC0MqwRKQ+JqYKfwbkERNQU2+47HjP8FmMKcqor4JoQTGNVyTtrMXVDuq2IM5CzJ6/PzUi0mrO4/pOi/JL66F/InXqs/G5ckHaJZIXGqipfObvO5Z7PYCXtBXmNWtAvUyTpXGibjwIiKUPryQy404WSc2wj26x30W6EyHNP/HE8MJpsCH+MdwtyGHp+3PLs3lUvwIDPpVj78MRKWIVnrDpp+XAYf6o/nMAG0vMkz6BMLW3BIupgFupalIO/1V55igD5HvBZRRAViDs2kV+CE/J+lZEmOFAVzQDd9iOYq+IugWt6/+qpb20N4lZpBr8V7Crfe58Ss4=
  - secure: oKl/xWdhnJ320rPph2+Ep8zmDh3lvo/Qh3fcCuWMb6q1fK0cEyvpGjknokzTkCveyOIHuzUJRHqy6YgDhHT4H86phHjXivNjCX2bxEtLLxbgsKa4WhZ67eTlYt3sNioqnKjt6M2DYT+/HRshyRcgk2/FQCQAW3R2fHbksF+oYfs++2GiuCrV4KnUJKE3bZWbunXt5S+5hkukTUqyzI5DfEaEiskj2XHi18loWvwe9srnpl5ucEduJJO55hqAVWCQv3OotXzXFn59GWW7Y+CO8kVsv5Okcelo1eU9WZFErapBVegTz+MYwxs4Y3ck8jKeCHhBDMitDHc5IgcjULyLMtuIzJLWoSaRy0BSTGLoYDK9Lnpacxnu7qZBb93DSCawHKGPyTGfPh6zlqZBKQBvcB3FXmZnxwVXS1HoMaWjxKNzr2jk5ohx7KElhy7uP3X5jzPrw2KqOwtrIRNBFQb8cBJyLP2mmz5f5/yNWMLmpisJi6x+y4Ppu0izzDIB+GRYLxG8E2mfaIMmhzjfWdM4K0jAE7zpTVXSy8W3qioh9ggjHDgw2jeNNkljPJBPfg388/RwRb95h/iqIK+04rCOjEtSpwLQP4JYyGqikE8UBrh5XVOmiuqP8LfRYUtfA9xThzlQwHli7HJ9icAN6gW/C0L0EE0PQCceOYb+etjsVmQ=
