language: go
go:
- 1.8.x
- tip
before_install:
- chmod +x test-coverage.sh
- go get -t -v ./...
script:
- "./test-coverage.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
# Generated encrypted environment variables of Geo API keys (won't work on forks/pull-request travis-ci builds): https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables
# travis encrypt ALSO_CLOUDUSER=XYZ --add
# travis encrypt ALSO_CLOUDPASSWORD=XYZ --add --append
  - secure: L8iGnBf4sZnqKGV4mlekwRzD+jHVUuIQ+hY/8v2HF1toGDNFuBU5ftoo9MdA5bU3JqFSouxje6ZwpQ/hKHvcXVQHAWs3kWAo+6BCg0PQNqD/LBXFd4WbvUawx9qz2/CwOrK7nOrki+1Ur6I96QMAcvNX0vegmCec7qIrSVC2nGcyqoPmA1+cLtbczkLOm+yA6lTyNXYCAs7tJZ1p2ny3CpG5HDXy3vdxM68Rdh4UkhtSBPikOFGbQnnVO048j8BBn3SwxtXPZN8ZSNl9WY6AlBYb6X3hA01piCmXa5JQcwd8rPOoEKopppmEaU4vczAsMFnG3232lhPm9CH/nQ7KOSoHVtam0nhSERLC0MqwRKQ+JqYKfwbkERNQU2+47HjP8FmMKcqor4JoQTGNVyTtrMXVDuq2IM5CzJ6/PzUi0mrO4/pOi/JL66F/InXqs/G5ckHaJZIXGqipfObvO5Z7PYCXtBXmNWtAvUyTpXGibjwIiKUPryQy404WSc2wj26x30W6EyHNP/HE8MJpsCH+MdwtyGHp+3PLs3lUvwIDPpVj78MRKWIVnrDpp+XAYf6o/nMAG0vMkz6BMLW3BIupgFupalIO/1V55igD5HvBZRRAViDs2kV+CE/J+lZEmOFAVzQDd9iOYq+IugWt6/+qpb20N4lZpBr8V7Crfe58Ss4=
  - secure: ooxbcLYAHFXw/qDr2v4/zR0jIbn3z6pAMy3Sbr3nsI5qsBs8+7l+EjZVCQsohOBMwgvDdeluxSxeGEqs/w35wyfVfFNvJIDMj/EjkWyq4cqvqyIlVwd/fxqQQEB74gGMFLX+aiyP7Xxb0VWTD1jpJpYM7QLuMo9QAwe162o/jU15oFCp3v/XzKRJUaA0LZYeEy66oAhTcROPTy34GytKPhWW3zv8VEHchFZSuCm7cEcp2+fhz/qXdmmswg6qJwXtynDT+4DMKnrJF81t6SLb+zQy4z16M9LaOgFmys0JwkrTDJiqnJttiRz9tFtQ/cHwYpagEeqRWSDPXqjXtuSNZweMYyHE3CPnDJI9frs61FB2z2/xeSMB4eH3iSCvi7gQ3P+o5IY3SJ5ZzY23u9CoZr2yKkMJceE1X+stiTd2yyXitC1JyBt7M/SmIYve+eDDt18uYpsT8GUZ66Z7RrYtuoJX0VfS3ynrRkFtSZEnc7+DVWjkUPYDOezuFom1Nf14ypNYBLjviu34T429QvI/HgLHqXZnBHP/P2vNdespIwl2CWSMlcNXlZqSFngXDJKbpUFZh5KzHN7BtI54Gbo/3+VFRCqb+TxC4O1evQEaMmmfbsgnXUlw0WVn8bTac+E5q3XSRTAwq5+jgi9kcqWvO2rYdRdZQIxhB7MvtpploqE=
